### PR TITLE
vm-allocator design implementation

### PR DESCRIPTION
**Pull request by liujing2**
@andreeaflorescu @sameo 
As discussed in the meeting on July 15th, I prepared vm-allocator patches from scratch. For easily reviewing, I split each functional module into separate commit. Let's quickly review the vm-allocator design for now and we can split them into several PRs later if we agree with the design.

BTW, I prefer to have an explicit repo for the vm-allocator PR later. :)

For quickly getting the information discussed before, some are listed as below.
- Proposal to implement system allocator in each VMM: 
https://github.com/rust-vmm/community/issues/33#issuecomment-511375675
https://github.com/rust-vmm/community/issues/33#issuecomment-511403087
- Proposal for spliting PR: https://github.com/rust-vmm/vm-device/pull/3#issuecomment-511389328

### CODE REVIEW

**Comment by liujing2** [comment]
@andreeaflorescu  @sameo  
The only issue is naming the resource. Since vmm knows which resources it would add, so both vm-device and vm-allocator should not care the resource name. As per such assuming, vm-allocator::DefaultSystemAllocator would be better to separate each allocator to one member instead of in hashmap. The same for vm-device::DeviceManager::xxx_allocate_cb closures.

**Comment by liujing2** [comment]
@andreeaflorescu  @sameo I add a README file to describe the design and different usage cases.

**Comment by sameo** [comment]
@liujing2: @andreeaflorescu will create a repo for the vm-allocator crate.

**Comment by sameo** [comment]
@liujing2 Done: See https://github.com/rust-vmm/vm-allocator.

Could you please move that PR there instead?

**Comment by andreeaflorescu** [comment]
@liujing2 I would like to close this PR. Do you have anything against it?

**Comment by liujing2** [comment]
> @liujing2 I would like to close this PR. Do you have anything against it?

Just close it please. Thanks!

**Pull request closed without merging**
